version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-llm
    working_dir: /app
    ports:
      - "8080:8000"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    restart: always
